# version: '4.29'

# services:
#   redis:
#     image: "redis:alpine"
#     ports:
#       - "6379:6379"
#     networks:
#       - app_network

#   mysql_server:
#     build:
#       context: ./mysqldb
#       dockerfile: Dockerfile
#     restart: always
#     env_file:
#       - .env
#     environment:
#       - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
#       - MYSQL_DATABASE=${DATABASE} 
#       - MYSQL_USER=${USER}
#       - MYSQL_PASSWORD=${PASSWORD}
#     # ports:
#     #   - "3306:3306"
#     healthcheck:
#       test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "root_password", "-e", "SELECT 1"]
#       timeout: 10s
#       retries: 10
#     networks:
#       - app_network
#         # ipv4_address: 172.20.0.2

#   recipesystem:
#     build:
#       context: ./django
#       dockerfile: Dockerfile
#     # command: python manage.py runserver 0.0.0.0:8000
#     command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
#     restart: always
#     volumes:
#       - ./django:/app
#       - ./AIML:/app/AIML
#     ports:
#       - "8000:8000"
#     depends_on:
#       mysql_server:
#         condition: service_healthy
#     networks:
#       - app_network

#   celery-worker:
#     build: ./django
#     command: celery -A recipesystem worker --loglevel=info
#     volumes:
#       - ./django:/app
#       - ./AIML:/app/AIML
#     depends_on:
#       - recipesystem
#       - redis
#     networks:
#       - app_network

#   celery-beat:
#     build: ./django
#     command: celery -A recipesystem beat --loglevel=info
#     volumes:
#       - ./django:/app
#       - ./AIML:/app/AIML
#     depends_on:
#       - recipesystem
#       - redis
#     networks:
#       - app_network

# networks:
#   app_network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16

version: '4.29'

services:

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app_network
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: '512M'
  #       reservations:
  #         memory: '256M'

  mysql_server:
    build:
      context: ./mysqldb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app_network

  recipesystem:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    tty: true
    restart: always
    volumes:
      - ./django:/app
      - ./AIML:/app/AIML
    ports:
      - "8000:8000"
    depends_on:
      - mysql_server
      # - redis
    networks:
      - app_network
    environment:
      - NLTK_DATA=/usr/share/nltk_data
    deploy:
      resources:
        limits:
          cpus: '3.50'
          memory: '3G'
        reservations:
          memory: '512M'
      
  # celery_worker:
  #   restart: always
  #   build: ./django
  #   user: celeryuser 
  #   command: celery -A recipesystem worker -l info -P gevent
  #   volumes:
  #     - ./django:/app
  #     - ./AIML:/app/AIML
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - DB_HOST=mysql_server
  #   depends_on:
  #     - recipesystem
  #     - redis
  #   networks:
  #     - app_network
  #   ports:
  #     - "5555:5555"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2.50'
  #         memory: '2G'
  #       reservations:
  #         memory: '512M'

  # celery_beat:
  #   restart: always
  #   build: ./django
  #   user: celeryuser 
  #   command: celery -A recipesystem beat -l info
  #   # command: celery -A recipesystem beat -l debug --pidfile=
  #   volumes:
  #     - ./django:/app
  #     - ./AIML:/app/AIML
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #     - DB_HOST=mysql_server
  #   depends_on:
  #     - recipesystem
  #     - redis
  #   networks:
  #     - app_network
  #   ports:
  #     - "8888:8888"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2.50'
  #         memory: '2G'
  #       reservations:
  #         memory: '256M'

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
