# Generated by Django 5.0.3 on 2024-07-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0007_history_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_column='date')),
                ('avg_like_status', models.BooleanField(db_column='avg_like_status', null=True)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
        migrations.CreateModel(
            name='RecommendedRecipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like_status', models.BooleanField(db_column='like_status', null=True)),
                ('recipeid', models.ForeignKey(db_column='recipeid', on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('recmd_id', models.ForeignKey(db_column='recmd_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recommend.recommendation')),
            ],
            options={
                'db_table': 'recommended_recipes',
            },
        ),
    ]
