# Generated by Django 5.0.3 on 2024-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_favorite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.URLField(default=''),
        ),
    ]
