# Generated by Django 5.0.3 on 2024-07-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
