# Generated by Django 5.0.3 on 2024-05-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'managed': False},
        ),
    ]
