# Generated by Django 5.0.3 on 2024-07-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_food_type_user_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
