# Generated by Django 5.0.3 on 2024-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_temp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
